### ISSUE TITLE
1.12.2: Plugin broken after latest updates

### ISSUE THREAD

**Issue by SladeHazard** [kangarko/Winter#54] opened 2021-12-02 19:17 UTC
The snow appears if I create a new world. But in my old worlds it's only appearing in some places.
If I add old version it starts working fine again.

realistic snow is set to false.
requires snow biome is set to false.

**Comment by SladeHazard** [comment] 2021-12-02 19:18
Please review your code , bug was introduced in version 3.0.2.

**Comment by kangarko** [comment] 2021-12-03 13:44
Duplicate of https://github.com/kangarko/Winter/issues/50

**Closed as completed by kangarko** 2021-12-03 13:44 UTC
Labels: issue
